import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp } from './workspace-canvas.helpers'

test.describe('Workspace Canvas - Agent Status Watcher', () => {
  test('updates an active agent from working to standby when the last session line has no newline', async () => {
    const { electronApp, window } = await launchApp({
      windowMode: 'offscreen',
      env: {
        COVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        COVE_TEST_AGENT_SESSION_SCENARIO: 'codex-standby-no-newline',
      },
    })

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'task-status-watch',
            title: 'Trace flaky status updates',
            position: { x: 180, y: 140 },
            width: 460,
            height: 280,
            kind: 'task',
            status: null,
            task: {
              requirement: 'Reproduce watcher status transitions and verify standby refresh',
              status: 'todo',
              priority: 'medium',
              tags: ['debug'],
              linkedAgentNodeId: null,
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-03-07T12:00:00.000Z',
              updatedAt: '2026-03-07T12:00:00.000Z',
            },
          },
        ],
        {
          settings: {
            defaultProvider: 'codex',
            customModelEnabledByProvider: {
              'claude-code': false,
              codex: true,
            },
            customModelByProvider: {
              'claude-code': '',
              codex: 'gpt-5.2-codex',
            },
            customModelOptionsByProvider: {
              'claude-code': [],
              codex: ['gpt-5.2-codex'],
            },
          },
        },
      )

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()

      await taskNode.locator('[data-testid="task-node-run-agent"]').click()

      const agentNode = window.locator('.terminal-node').first()
      const nodeStatus = agentNode.locator('.terminal-node__status')
      const sidebarStatus = window
        .locator('.workspace-sidebar .workspace-agent-item .workspace-agent-item__status--agent')
        .first()
      const taskStatus = taskNode.locator('[data-testid="task-node-status-select"]')

      await expect(agentNode).toBeVisible()
      await expect(taskStatus).toHaveValue('doing')
      await expect(agentNode).toContainText('[cove-test-agent] codex new')
      await expect(nodeStatus).toHaveText('Running')
      await expect(sidebarStatus).toHaveText('Working')
      await expect(nodeStatus).toHaveText('Standby', { timeout: 15_000 })
      await expect(sidebarStatus).toHaveText('Standby')
    } finally {
      await electronApp.close()
    }
  })
})
