import type { Node } from '@xyflow/react'
import type {
  ImageNodeData,
  NoteNodeData,
  PgViewerNodeData,
  PersistedWorkspaceState,
  TaskNodeData,
  TerminalNodeData,
} from '../types'

function isTaskNodeData(
  value: TaskNodeData | NoteNodeData | ImageNodeData | PgViewerNodeData | null,
): value is TaskNodeData {
  return value !== null && typeof value === 'object' && 'requirement' in value
}

function isNoteNodeData(
  value: TaskNodeData | NoteNodeData | ImageNodeData | PgViewerNodeData | null,
): value is NoteNodeData {
  return value !== null && typeof value === 'object' && 'text' in value
}

function isImageNodeData(
  value: TaskNodeData | NoteNodeData | ImageNodeData | PgViewerNodeData | null,
): value is ImageNodeData {
  return value !== null && typeof value === 'object' && 'assetId' in value && 'mimeType' in value
}

function isPgViewerNodeData(
  value: TaskNodeData | NoteNodeData | ImageNodeData | PgViewerNodeData | null,
): value is PgViewerNodeData {
  return value !== null && typeof value === 'object' && 'host' in value && 'database' in value && 'isConnected' in value
}

export function toRuntimeNodes(workspace: PersistedWorkspaceState): Node<TerminalNodeData>[] {
  return workspace.nodes.map(node => {
    const defaultTask: TaskNodeData = {
      requirement: '',
      status: 'todo',
      priority: 'medium',
      tags: [],
      linkedAgentNodeId: null,
      agentSessions: [],
      lastRunAt: null,
      autoGeneratedTitle: false,
      createdAt: null,
      updatedAt: null,
    }
    const task: TaskNodeData | null =
      node.kind === 'task' ? (isTaskNodeData(node.task) ? node.task : defaultTask) : null
    const note =
      node.kind === 'note' ? (isNoteNodeData(node.task) ? node.task : { text: '' }) : null
    const image: ImageNodeData | null =
      node.kind === 'image' ? (isImageNodeData(node.task) ? node.task : null) : null
    const pgViewer: PgViewerNodeData | null =
      node.kind === 'pgViewer'
        ? isPgViewerNodeData(node.task)
          ? { ...node.task, connectionId: null, isConnected: false, activeTable: null }
          : { connectionId: null, host: 'localhost', port: 5432, database: '', user: '', isConnected: false, activeTable: null }
        : null

    const runtimeNode: Node<TerminalNodeData> = {
      id: node.id,
      type:
        node.kind === 'task'
          ? 'taskNode'
          : node.kind === 'note'
            ? 'noteNode'
            : node.kind === 'image'
              ? 'imageNode'
              : node.kind === 'pgViewer'
                ? 'pgViewerNode'
                : 'terminalNode',
      position: node.position,
      data: {
        sessionId: '',
        profileId: node.profileId,
        runtimeKind: node.runtimeKind,
        labelColorOverride: node.labelColorOverride ?? null,
        title: node.title,
        titlePinnedByUser: node.titlePinnedByUser === true,
        width: node.width,
        height: node.height,
        kind: node.kind,
        status: node.status,
        startedAt: node.startedAt,
        endedAt: node.endedAt,
        exitCode: node.exitCode,
        lastError: node.lastError,
        scrollback: node.scrollback,
        executionDirectory: node.executionDirectory,
        expectedDirectory: node.expectedDirectory,
        agent: node.agent,
        task,
        note,
        image,
        pgViewer,
      },
      draggable: true,
      selectable: node.kind !== 'note',
    }

    return runtimeNode
  })
}
